- name: Configure Docker on EC2 Instance (Local)
  hosts: localhost
  become: true
  tasks:
    - name: Remove conflicting containerd (if exists)
      apt:
        name: containerd
        state: absent
      ignore_errors: true

    - name: Remove existing Docker repo (if exists)
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: true

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Ensure Jenkins user is in docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Pull Docker Image
      docker_image:
        name: jayasurya0199/staragilefinancev1
        tag: latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: staragilefinance-app
        image: jayasurya0199/staragilefinancev1:latest
        state: started
        ports:
          - "8085:8081"

